export const TAG_DESCRIPTIONS: Record<string, string> = {
  Linux: "Système d'exploitation open source",
  Apache: 'Serveur web HTTP / HTTPS',
  Bash: 'Scripting shell Unix/Linux',
  SSL: 'Chiffrement et certificats HTTPS',
  VMware: 'Hyperviseur de virtualisation',
  Réseau: 'Configuration LAN / WAN',
  pfSense: 'Pare-feu BSD open source',
  VLAN: 'Segmentation réseau logique',
  Python: 'Langage de programmation polyvalent',
  'TI-Python': 'Python embarqué sur calculatrice TI',
  JSON: "Format d'échange de données léger",
  'C#': 'Langage orienté objet Microsoft',
  '.NET': 'Framework applicatif Microsoft',
  Debugging: 'Analyse et correction de bugs',
  'Kali Linux': 'Distribution Linux pour le pentesting',
  Nmap: "Scanner de ports et d'hôtes réseau",
  Pentesting: "Tests d'intrusion autorisés",
  'HTML/CSS': 'Langages de structure et de style web',
  o2switch: 'Hébergement mutualisé français',
  JavaScript: 'Langage de script côté client',
  PHP: 'Langage de script côté serveur',
  MySQL: 'Système de gestion de base de données',
  Git: 'Logiciel de gestion de versions',
  Docker: 'Plateforme de conteneurisation',
  'Active Directory': "Service d'annuaire Microsoft",
  'Windows Server': "Système d'exploitation serveur Microsoft",
  GPO: 'Group Policy Object — Stratégies de groupes',
  DNS: 'Domain Name System — Résolution de noms',
}
